CREATE TYPE severity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

CREATE TABLE tenant_rules (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              rule_id BIGINT NOT NULL UNIQUE,
                              rule_code VARCHAR(255) NOT NULL UNIQUE,
                              rule_name VARCHAR(255) NOT NULL UNIQUE,
                              description TEXT NOT NULL,
                              severity_rate severity NOT NULL,
                              is_active BOOLEAN NOT NULL,
                              is_deleted BOOLEAN DEFAULT FALSE,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              CONSTRAINT fk_rule_template
                                  FOREIGN KEY (rule_id)
                                      REFERENCES public.rule_templates(id)
);

CREATE TYPE user_role AS ENUM ('compliance_officer', 'bank_admin');
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       system_user_id BIGINT REFERENCES public.system_users(id),
                       first_name VARCHAR(255) NOT NULL,
                       middle_name VARCHAR(255),
                       last_name VARCHAR(255) NOT NULL,
                       employee_code VARCHAR(100) UNIQUE NOT NULL,

    -- Using the custom enum types
                       role user_role NOT NULL,
    -- Audit fields
                       created_by BIGINT REFERENCES public.system_users(id),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       deactivated_at TIMESTAMP
);

CREATE TABLE rule_parameters (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 rule_id BIGINT NOT NULL,
                                 param_key VARCHAR(255) NOT NULL,
                                 param_value VARCHAR(255) NOT NULL,
                                 min_value VARCHAR(255),
                                 max_value VARCHAR(255),
                                 is_deleted BOOLEAN DEFAULT FALSE,
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_rule
                                     FOREIGN KEY (rule_id)
                                         REFERENCES tenant_rules(id)
                                         ON DELETE CASCADE
);

CREATE TABLE rule_version_parameters (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         rule_param_id BIGINT REFERENCES rule_parameters(id),
                                         param_key VARCHAR(255) NOT NULL,
                                         old_param_value VARCHAR(255) NOT NULL,
                                         new_param_value VARCHAR(255) NOT NULL,
                                         changed_by BIGINT REFERENCES users(id),
                                         is_deleted BOOLEAN DEFAULT FALSE,
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TYPE batch_status AS ENUM ('uploaded', 'processing', 'completed');
CREATE TABLE batches (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uploaded_by BIGINT NOT NULL,
                                     is_deleted BOOLEAN DEFAULT FALSE,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                     CONSTRAINT fk_uploaded_by
                                         FOREIGN KEY (uploaded_by)
                                             REFERENCES users(id)
);
CREATE TABLE files(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      batch_id BIGINT NOT NULL,
                      file_name VARCHAR(255) NOT NULL,
                      file_storage_path VARCHAR(500),
                      file_size_bytes BIGINT NOT NULL,
                      total_records INTEGER NOT NULL,
                      status batch_status NOT NULL DEFAULT 'uploaded',
                      processed_at TIMESTAMP,
                      is_removed BOOLEAN DEFAULT FALSE,
                      is_deleted BOOLEAN DEFAULT FALSE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                      CONSTRAINT fk_file_batch
                          FOREIGN KEY (batch_id)
                              REFERENCES batches(id)
                              ON DELETE CASCADE
);
CREATE TABLE file_validation_errors (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         file_id BIGINT NOT NULL,
                                         row_number INTEGER NOT NULL,
                                         field_name VARCHAR(255),
                                         error_message VARCHAR(500) NOT NULL,
                                         is_deleted BOOLEAN DEFAULT FALSE,
                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                         CONSTRAINT fk_batch_validation_error
                                             FOREIGN KEY (file_id)
                                                 REFERENCES files(id)
                                                 ON DELETE CASCADE
);

CREATE TYPE transaction_type AS ENUM ('debit', 'credit');
CREATE TYPE transaction_mode AS ENUM ('cash', 'net_banking', 'upi', 'cheque');

CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              batch_id BIGINT NOT NULL,
                              file_id BIGINT NOT NULL,
                              account_number VARCHAR(12) NOT NULL,
                              counter_party_account_number VARCHAR(12),
                              transaction_date DATE,
                              transaction_type transaction_type NOT NULL ,
                              transaction_mode transaction_mode NOT NULL ,
                              amount DECIMAL(19, 2) NOT NULL,
                              transaction_reference_number VARCHAR(18) NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              is_deleted BOOLEAN DEFAULT FALSE,

                              CONSTRAINT fk_batch_transaction
                                  FOREIGN KEY (batch_id)
                                      REFERENCES batches(id)
                                      ON DELETE CASCADE,
                              CONSTRAINT fk_file_transaction
                                  FOREIGN KEY (file_id)
                                      REFERENCES files(id)
                                      ON DELETE CASCADE
);


CREATE TYPE occupation_type_enum AS ENUM (
    'salaried',
    'student',
    'business',
    'self_employed',
    'retired',
    'unemployed'
);

-- 2. Create the Customers table
CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           client_number VARCHAR(255) UNIQUE NOT NULL,
                           first_name VARCHAR(255) NOT NULL,
                           last_name VARCHAR(255) NOT NULL,
                           middle_name VARCHAR(255),
                           aadhar_number VARCHAR(12) NOT NULL UNIQUE,
                           pan VARCHAR(10) NOT NULL UNIQUE,
                           occupation VARCHAR(255) NOT NULL,
                           occupation_type occupation_type_enum NOT NULL,
                           is_pep BOOLEAN,
                           risk_rate severity,
                           monthly_income DECIMAL(19, 2) NOT NULL,
                           dob DATE NOT NULL,
                           profession_multiplier DECIMAL(5, 2),
                           family_code VARCHAR(255),
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TYPE account_type AS ENUM ('current', 'saving', 'salary', 'fd');
CREATE TYPE account_status AS ENUM ('active', 'inactive', 'frozen', 'dormant', 'closed');

CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          client_number VARCHAR(255) NOT NULL,
                          account_number VARCHAR(12) NOT NULL UNIQUE,
                          account_type account_type NOT NULL,
                          account_status account_status NOT NULL DEFAULT 'active',
                          is_deleted BOOLEAN DEFAULT FALSE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE case_status AS ENUM (
    'open', 'pending_review', 'under_investigation', 'on_hold',
    'escalated', 'closed_as_false_positive', 'reported_to_fiu', 'closed'
);

CREATE TABLE cases (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       case_reference_number VARCHAR(8) NOT NULL UNIQUE,
                       status case_status NOT NULL DEFAULT 'open',
                       assigned_to BIGINT,
                       assigned_by BIGINT,
                       closed_at TIMESTAMP,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       notes TEXT,
                       is_deleted BOOLEAN DEFAULT FALSE,

                       CONSTRAINT fk_case_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id),
                       CONSTRAINT fk_case_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id)
);

CREATE TYPE alert_status AS ENUM ('new', 'dismissed', 'converted_to_case');

CREATE TABLE alerts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        rule_id BIGINT NOT NULL,
                        case_id BIGINT,
                        status alert_status NOT NULL DEFAULT 'new',
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        is_deleted BOOLEAN DEFAULT FALSE,

                        CONSTRAINT fk_alert_rule FOREIGN KEY (rule_id) REFERENCES tenant_rules(id),
                        CONSTRAINT fk_alert_case FOREIGN KEY (case_id) REFERENCES cases(id)
);
CREATE TABLE transaction_alerts (
    transaction_id BIGINT NOT NULL REFERENCES transactions(id),
    alert_id BIGINT NOT NULL REFERENCES alerts(id),
    PRIMARY KEY (transaction_id, alert_id)
);

CREATE TABLE str_filings (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             case_id BIGINT NOT NULL UNIQUE ,
                             filed_by BIGINT NOT NULL,
                             supporting_notes TEXT,
                             reference_number VARCHAR(8) NOT NULL UNIQUE,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             pdf_storage_path VARCHAR(500) NOT NULL UNIQUE,
                             is_deleted BOOLEAN DEFAULT FALSE,

                             CONSTRAINT fk_str_case FOREIGN KEY (case_id) REFERENCES cases(id),
                             CONSTRAINT fk_str_user FOREIGN KEY (filed_by) REFERENCES users(id)
);

CREATE TYPE notification_type AS ENUM (
    'alert_generated', 'case_assigned', 'case_escalated', 'str_filed', 'batch_failed'
);

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               notification_type notification_type NOT NULL,
                               related_record_id BIGINT,
                               related_record_table_name VARCHAR(100),
                               message TEXT NOT NULL,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               is_deleted BOOLEAN DEFAULT FALSE,

                               CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id)
);