CREATE TABLE tenant_rules (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              rule_id INTEGER NOT NULL UNIQUE,
                              rule_code VARCHAR(255) NOT NULL UNIQUE,
                              rule_name VARCHAR(255) NOT NULL UNIQUE,
                              description TEXT NOT NULL,
                              severity_rate INTEGER NOT NULL,
                              is_active BOOLEAN NOT NULL,
                              is_deleted BOOLEAN DEFAULT FALSE,
                              CONSTRAINT fk_rule_template
                                  FOREIGN KEY (rule_id)
                                      REFERENCES public.rule_templates(id)
);

CREATE TYPE user_role AS ENUM ('compliance_officer', 'bank_admin');
CREATE TYPE user_status AS ENUM ('active', 'inactive');
CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       full_name VARCHAR(255) NOT NULL,
                       employee_code VARCHAR(100) UNIQUE NOT NULL,

    -- Using the custom enum types
                       role user_role NOT NULL,
                       status user_status NOT NULL,

                       failed_login_attempts INTEGER DEFAULT 0 NOT NULL,
                       last_login_at TIMESTAMP,

    -- Audit fields
                       created_by INTEGER REFERENCES public.system_users(id),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       deactivated_at TIMESTAMP,
                       is_active BOOLEAN DEFAULT TRUE,
                       is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE rule_parameters (
                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 rule_id INTEGER NOT NULL,
                                 param_key VARCHAR(255) NOT NULL,
                                 param_value VARCHAR(255) NOT NULL,
                                 min_value VARCHAR(255),
                                 max_value VARCHAR(255),
                                 is_deleted BOOLEAN DEFAULT FALSE,

                                 CONSTRAINT fk_rule
                                     FOREIGN KEY (rule_id)
                                         REFERENCES tenant_rules(id)
                                         ON DELETE CASCADE
);

CREATE TABLE rule_version_parameters (
                                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         rule_param_id INTEGER REFERENCES rule_parameters(id),
                                         param_key VARCHAR(255) NOT NULL,
                                         old_param_value VARCHAR(255) NOT NULL,
                                         new_param_value VARCHAR(255) NOT NULL,
                                         changed_by INTEGER REFERENCES users(id),
                                         changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         is_deleted BOOLEAN DEFAULT FALSE
);
CREATE TYPE batch_status AS ENUM ('uploaded', 'processing', 'completed');
CREATE TABLE transaction_batches (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     uploaded_by INTEGER NOT NULL,
                                     file_name VARCHAR(255) NOT NULL,
                                     file_storage_path VARCHAR(500) NOT NULL,
                                     total_records INTEGER NOT NULL,
                                     status batch_status NOT NULL DEFAULT 'uploaded',
                                     uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     processed_at TIMESTAMP,
                                     is_deleted BOOLEAN DEFAULT FALSE,

                                     CONSTRAINT fk_uploaded_by
                                         FOREIGN KEY (uploaded_by)
                                             REFERENCES users(id)
);
CREATE TABLE batch_validation_errors (
                                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         batch_id INTEGER NOT NULL,
                                         row_number INTEGER NOT NULL,
                                         field_name VARCHAR(255),
                                         error_message VARCHAR(500) NOT NULL,

                                         CONSTRAINT fk_batch_validation_error
                                             FOREIGN KEY (batch_id)
                                                 REFERENCES transaction_batches(id)
                                                 ON DELETE CASCADE
);

CREATE TYPE transaction_type AS ENUM ('debit', 'credit');
CREATE TYPE transaction_mode AS ENUM ('cash', 'net_banking', 'upi', 'cheque');

CREATE TABLE transactions (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              batch_id INTEGER NOT NULL,
                              account_number VARCHAR(255) NOT NULL,
                              transaction_date DATE,
                              transaction_type transaction_type,
                              transaction_mode transaction_mode,
                              amount DECIMAL(19, 2) NOT NULL,
                              transaction_reference_number VARCHAR(255) NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              is_deleted BOOLEAN DEFAULT FALSE,

                              CONSTRAINT fk_batch_transaction
                                  FOREIGN KEY (batch_id)
                                      REFERENCES transaction_batches(id)
                                      ON DELETE CASCADE
);

CREATE TYPE occupation_type_enum AS ENUM (
    'salaried',
    'student',
    'business',
    'self_employed',
    'retired',
    'unemployed'
);

-- 2. Create the Customers table
CREATE TABLE customers (
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           client_id VARCHAR(255) UNIQUE NOT NULL,
                           first_name VARCHAR(255) NOT NULL,
                           last_name VARCHAR(255) NOT NULL,
                           middle_name VARCHAR(255),
                           aadhaar_number VARCHAR(12) NOT NULL UNIQUE,
                           pan VARCHAR(10) NOT NULL UNIQUE,
                           occupation VARCHAR(255) NOT NULL,
                           occupation_type occupation_type_enum NOT NULL,
                           is_pep BOOLEAN DEFAULT FALSE,
                           risk_rate INTEGER CHECK (risk_rate >= 1 AND risk_rate <= 10),
                           monthly_income DECIMAL(19, 2) NOT NULL,
                           dob DATE NOT NULL,
                           profession_multiplier DECIMAL(5, 2),
                           family_code VARCHAR(255),
                           is_deleted BOOLEAN DEFAULT FALSE
);

CREATE TYPE account_type AS ENUM ('current', 'saving', 'salary', 'fd');
CREATE TYPE account_status AS ENUM ('active', 'inactive', 'frozen', 'dormant', 'closed');

CREATE TABLE accounts (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          client_id VARCHAR(255) NOT NULL,
                          account_number VARCHAR(255) NOT NULL UNIQUE,
                          account_type account_type NOT NULL,
                          account_status account_status NOT NULL DEFAULT 'active',
                          is_deleted BOOLEAN DEFAULT FALSE,

                          CONSTRAINT fk_account_customer
                              FOREIGN KEY (client_id)
                                  REFERENCES customers(client_id)
);

CREATE TYPE case_status AS ENUM (
    'open', 'pending_review', 'under_investigation', 'on_hold',
    'escalated', 'closed_as_false_positive', 'reported_to_fiu', 'closed'
);

CREATE TABLE cases (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       case_reference_number VARCHAR(255) NOT NULL UNIQUE,
                       status case_status NOT NULL DEFAULT 'open',
                       assigned_to INTEGER,
                       assigned_by INTEGER,
                       assigned_at TIMESTAMP,
                       closed_at TIMESTAMP,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       notes TEXT,
                       is_deleted BOOLEAN DEFAULT FALSE,

                       CONSTRAINT fk_case_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id),
                       CONSTRAINT fk_case_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id)
);

CREATE TYPE alert_status AS ENUM ('new', 'dismissed', 'converted_to_case');

CREATE TABLE alerts (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        transaction_id INTEGER NOT NULL,
                        rule_id INTEGER NOT NULL,
                        case_id INTEGER,
                        status alert_status NOT NULL DEFAULT 'new',
                        generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        is_deleted BOOLEAN DEFAULT FALSE,

                        CONSTRAINT fk_alert_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id),
                        CONSTRAINT fk_alert_rule FOREIGN KEY (rule_id) REFERENCES tenant_rules(id),
                        CONSTRAINT fk_alert_case FOREIGN KEY (case_id) REFERENCES cases(id)
);

CREATE TABLE str_filings (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             case_id INTEGER NOT NULL,
                             filed_by INTEGER NOT NULL,
                             supporting_notes TEXT,
                             reference_number VARCHAR(255) NOT NULL UNIQUE,
                             submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             pdf_storage_path VARCHAR(500) NOT NULL,
                             is_deleted BOOLEAN DEFAULT FALSE,

                             CONSTRAINT fk_str_case FOREIGN KEY (case_id) REFERENCES cases(id),
                             CONSTRAINT fk_str_user FOREIGN KEY (filed_by) REFERENCES users(id)
);

CREATE TYPE event_type AS ENUM (
    'alert_generated', 'case_assigned', 'case_escalated', 'str_filed', 'batch_failed'
);

CREATE TABLE notifications (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id INTEGER NOT NULL,
                               event_type event_type NOT NULL,
                               related_record_id INTEGER,
                               related_record_table_name VARCHAR(100),
                               message TEXT NOT NULL,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               is_deleted BOOLEAN DEFAULT FALSE,

                               CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id)
);