spring.application.name=AmlSystem
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.multi_tenancy_strategy=SCHEMA
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

app.jwtSecret=${JWT_SECRET}
# 3600000 ms = 1 hour
app.jwtExpirationMs=${JWT_EXPIRATION_MS}
# 86400000 ms = 24 hours (for Refresh Token)
app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

# Batch configuration
spring.batch.job.enabled=false

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
# SMTP Server Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

