spring.application.name=AmlSystem
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

app.jwtSecret=${JWT_SECRET}
# 3600000 ms = 1 hour
app.jwtExpirationMs=${JWT_EXPIRATION_MS}
# 86400000 ms = 24 hours (for Refresh Token)
app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

