package com.tss.AmlSystem.entity.enums;

public enum AuditActionType {
    LOGIN,
    LOGIN_FAILED,
    PASSWORD_CHANGE,
    USER_CREATED,
    USER_DEACTIVATED,
    TENANT_CREATED,
    TENANT_DEACTIVATED,
    RULE_ASSIGNED,
    RULE_REVOKED,
    BATCH_UPLOADED,
    BATCH_PROCESSING_STARTED,
    BATCH_PROCESSING_COMPLETED,
    BATCH_FAILED,
    ALERT_GENERATED,
    CASE_CREATED,
    CASE_ASSIGNED,
    CASE_CLOSED,
    STR_CREATED
}
