package com.tss.AmlSystem.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import com.tss.AmlSystem.dto.pdf.StrAlertDto;
import com.tss.AmlSystem.dto.pdf.StrCustomerDto;
import com.tss.AmlSystem.dto.pdf.StrReportDto;
import com.tss.AmlSystem.dto.pdf.StrTransactionDto;
import com.tss.AmlSystem.entity.tenant.Transaction;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import com.lowagie.text.PageSize;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
@RequiredArgsConstructor
public class PdfGenerationService {

    private final TemplateEngine templateEngine;

    public byte[] generateTransactionReport(List<Transaction> transactions) {
        // 1. Create a stream to hold the PDF data
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        // 2. Initialize the Document and Writer
        Document document = new Document(PageSize.A4.rotate()); // .rotate() makes it Landscape
        PdfWriter.getInstance(document, outputStream);

        // 3. Open the document to start writing
        document.open();

        // 4. Add a Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Paragraph title = new Paragraph("Customer Transaction Report", titleFont);
        title.setSpacingAfter(20);
        document.add(title);

        // 5. Create a Table (e.g., 3 columns: Date, Description, Amount)
        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(100);

        float[] columnWidths = {1.4f, 3.2f, 1.8f, 2.0f, 1.2f, 0.8f, 1.6f};
        table.setWidths(columnWidths);

        table.getDefaultCell().setPaddingTop(8f);
        table.getDefaultCell().setPaddingBottom(8f);

        // Optional but recommended: Center the text vertically so it doesn't hug the top edge
        table.getDefaultCell().setVerticalAlignment(com.lowagie.text.Element.ALIGN_MIDDLE);
        // -----------------------------------------

        // Add Table Headers
        table.addCell("Date");
        table.addCell("Ref_Number");
        table.addCell("Acc_Number");
        table.addCell("Receiver_Acc_Number");
        table.addCell("Amount");
        table.addCell("Type");
        table.addCell("Mode");


        // 6. Populate Table Rows with Transaction Data
        for (Transaction txn : transactions) {
            table.addCell(txn.getTransactionDate().toString());
            table.addCell(txn.getTransactionReferenceNumber());
            table.addCell(txn.getAccountNumber());
            table.addCell(txn.getCounterPartyAccountNumber());
            table.addCell(txn.getAmount().toString());
            table.addCell(txn.getTransactionType().toString());
            table.addCell(txn.getTransactionMode().toString());
        }

        // 7. Add table to document and close
        document.add(table);
        document.close();

        // 8. Return the generated byte array
        return outputStream.toByteArray();
    }

    public byte[] generateStrReportPdf(StrReportDto reportDto, StrCustomerDto customerDto, List<StrAlertDto> alertDtoList, List<StrTransactionDto> transactionDtoList) {

        Context context = new Context();

        context.setVariable("report", reportDto);
        context.setVariable("customer", customerDto);
        context.setVariable("alerts", alertDtoList);
        context.setVariable("transactions", transactionDtoList);

        String htmlContent = templateEngine.process("str-report", context);

        // 3. Convert HTML String to PDF Byte Array
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PdfRendererBuilder builder = new PdfRendererBuilder();

            // "classpath:/" helps the builder find any local resources if you add images/fonts later
            builder.withHtmlContent(htmlContent, getClass().getResource("/").toExternalForm());
            builder.useFastMode();
            builder.toStream(outputStream);
            builder.run();

            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF", e);
        }
    }
}
