package com.tss.AmlSystem.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.tss.AmlSystem.entity.tenant.Transaction;
import org.springframework.stereotype.Service;
import com.lowagie.text.PageSize;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfGenerationService {

    public byte[] generateTransactionReport(List<Transaction> transactions) {
        // 1. Create a stream to hold the PDF data
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        // 2. Initialize the Document and Writer
        Document document = new Document(PageSize.A4.rotate()); // .rotate() makes it Landscape
        PdfWriter.getInstance(document, outputStream);

        // 3. Open the document to start writing
        document.open();

        // 4. Add a Title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Paragraph title = new Paragraph("Customer Transaction Report", titleFont);
        title.setSpacingAfter(20);
        document.add(title);

        // 5. Create a Table (e.g., 3 columns: Date, Description, Amount)
        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(100);

        float[] columnWidths = {1.4f, 3.2f, 1.8f, 2.0f, 1.2f, 0.8f, 1.6f};
        table.setWidths(columnWidths);

        table.getDefaultCell().setPaddingTop(8f);
        table.getDefaultCell().setPaddingBottom(8f);

        // Optional but recommended: Center the text vertically so it doesn't hug the top edge
        table.getDefaultCell().setVerticalAlignment(com.lowagie.text.Element.ALIGN_MIDDLE);
        // -----------------------------------------

        // Add Table Headers
        table.addCell("Date");
        table.addCell("Ref_Number");
        table.addCell("Acc_Number");
        table.addCell("Receiver_Acc_Number");
        table.addCell("Amount");
        table.addCell("Type");
        table.addCell("Mode");


        // 6. Populate Table Rows with Transaction Data
        for (Transaction txn : transactions) {
            table.addCell(txn.getTransactionDate().toString());
            table.addCell(txn.getTransactionReferenceNumber());
            table.addCell(txn.getAccountNumber());
            table.addCell(txn.getCounterPartyAccountNumber());
            table.addCell(txn.getAmount().toString());
            table.addCell(txn.getTransactionType().toString());
            table.addCell(txn.getTransactionMode().toString());
        }

        // 7. Add table to document and close
        document.add(table);
        document.close();

        // 8. Return the generated byte array
        return outputStream.toByteArray();
    }
}
